packages:
  - packages/*
  - services/*
catalog:
  '@ai-sdk/openai': ^1.3.6
  '@fisch0920/config': ^1.0.2
  '@modelcontextprotocol/sdk': ^1.8.0
  '@types/node': ^22.14.0
  ai: ^4.2.11
  cleye: ^1.3.4
  del-cli: ^6.0.0
  dotenv: ^16.4.7
  eslint: ^9.23.0
  exit-hook: ^4.0.0
  ky: ^1.8.0
  lint-staged: ^15.5.0
  npm-run-all2: ^7.0.2
  only-allow: ^1.2.1
  p-map: ^7.0.3
  p-throttle: 6.2.0 # pinned for now
  prettier: ^3.5.3
  restore-cursor: ^5.1.0
  simple-git-hooks: ^2.12.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: ^2.5.0
  type-fest: ^4.39.1
  typescript: ^5.8.2
  vitest: ^3.1.1
  zod: ^3.24.2
