packages:
  - packages/*
  - apps/*
  - packages/fixtures/valid/*
onlyBuiltDependencies:
  - '@sentry/cli'
catalog:
  '@agentic/openauth': ^0.4.3
  '@ai-sdk/openai': ^1.3.22
  '@apideck/better-ajv-errors': ^0.3.6
  '@clack/prompts': ^0.11.0
  '@cloudflare/workers-types': ^4.20250610.0
  '@commander-js/extra-typings': ^14.0.0
  '@edge-runtime/vm': ^5.0.0
  '@fisch0920/config': ^1.1.2
  '@fisch0920/drizzle-orm': ^0.43.7
  '@fisch0920/drizzle-zod': ^0.7.9
  '@hono/node-server': ^1.14.4
  '@hono/sentry': ^1.2.2
  '@hono/zod-openapi': ^0.19.8
  '@hono/zod-validator': ^0.7.0
  '@modelcontextprotocol/sdk': ^1.12.1
  '@paralleldrive/cuid2': ^2.2.2
  '@react-email/components': ^0.0.42
  '@redocly/openapi-core': ^1.34.3
  '@sentry/cli': ^2.46.0
  '@sentry/cloudflare': ^9.28.1
  '@sentry/core': ^9.28.1
  '@sentry/node': ^9.28.1
  '@types/ms': ^2.1.0
  '@types/node': ^22.15.29
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/semver': ^7.7.0
  agents: ^0.0.95
  ai: ^4.3.15
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  camelcase: ^8.0.0
  cleye: ^1.3.4
  commander: ^14.0.0
  conf: ^14.0.0
  decamelize: ^6.0.0
  del-cli: ^6.0.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  email-validator: ^2.0.4
  eslint: ^9.28.0
  eslint-plugin-drizzle: ^0.2.3
  eventid: ^2.0.1
  exit-hook: ^4.0.0
  fast-content-type-parse: ^3.0.0
  fast-uri: ^3.0.6
  fastmcp: ^3.1.1
  get-port: ^7.1.0
  hash-object: ^5.0.1
  hono: ^4.7.11
  is-relative-url: ^4.0.0
  knip: ^5.60.2
  ky: ^1.8.1
  lint-staged: ^16.1.0
  ms: ^2.1.3
  npm-run-all2: ^8.0.4
  octokit: ^5.0.3
  only-allow: ^1.2.1
  open: ^10.1.2
  openapi-typescript: ^7.8.0
  ora: ^8.2.0
  p-all: ^5.0.0
  p-map: ^7.0.3
  p-throttle: 7.0.0
  parse-json: ^8.3.0
  plur: ^5.1.0
  postgres: ^3.4.7
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  react-email: ^4.0.16
  resend: ^4.5.2
  restore-cursor: ^5.1.0
  semver: ^7.7.2
  simple-git-hooks: ^2.13.0
  sort-keys: ^5.1.0
  stripe: ^18.2.1
  tsup: ^8.5.0
  tsx: ^4.20.1
  turbo: ^2.5.4
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unconfig: ^7.3.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.3
  wrangler: ^4.19.2
  zod: ^3.25.62
  zod-to-json-schema: ^3.24.5
  zod-validation-error: ^3.4.1
