packages:
  - packages/*
  - apps/*

catalog:
  '@ai-sdk/openai': ^1.3.22
  '@fisch0920/config': ^1.1.0
  '@modelcontextprotocol/sdk': ^1.11.2
  '@types/node': ^22.15.18
  ai: ^4.3.15
  cleye: ^1.3.4
  del-cli: ^6.0.0
  dotenv: ^16.5.0
  eslint: ^9.27.0
  exit-hook: ^4.0.0
  ky: ^1.8.1
  lint-staged: ^16.0.0
  npm-run-all2: ^8.0.1
  only-allow: ^1.2.1
  p-map: ^7.0.3
  p-throttle: 7.0.0
  prettier: ^3.5.3
  restore-cursor: ^5.1.0
  simple-git-hooks: ^2.13.0
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.3
  type-fest: ^4.41.0
  typescript: ^5.8.3
  vitest: ^3.1.3
  zod: ^3.25.30
