packages:
  - packages/*
  - apps/*
catalog:
  "@ai-sdk/openai": ^1.3.22
  "@clack/prompts": ^0.11.0
  "@commander-js/extra-typings": ^14.0.0
  "@fisch0920/config": ^1.1.0
  "@fisch0920/drizzle-orm": ^0.43.7
  "@fisch0920/drizzle-zod": ^0.7.9
  "@hono/node-server": ^1.14.3
  "@hono/sentry": ^1.2.1
  "@hono/zod-openapi": ^0.19.7
  "@hono/zod-validator": ^0.6.0
  "@modelcontextprotocol/sdk": ^1.12.1
  "@openauthjs/openauth": ^0.4.3
  "@paralleldrive/cuid2": ^2.2.2
  "@redocly/openapi-core": ^1.34.3
  "@sentry/node": ^9.23.0
  "@types/ms": ^2.1.0
  "@types/node": ^22.15.24
  "@types/semver": ^7.7.0
  ai: ^4.3.15
  camelcase: ^8.0.0
  cleye: ^1.3.4
  commander: ^14.0.0
  conf: ^13.1.0
  decamelize: ^6.0.0
  del-cli: ^6.0.0
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.43.1
  email-validator: ^2.0.4
  eslint: ^9.27.0
  eslint-plugin-drizzle: ^0.2.3
  eventid: ^2.0.1
  exit-hook: ^4.0.0
  get-port: ^7.1.0
  hash-object: ^5.0.1
  hono: ^4.7.10
  is-relative-url: ^4.0.0
  knip: ^5.59.1
  ky: ^1.8.1
  lint-staged: ^16.1.0
  ms: ^2.1.3
  npm-run-all2: ^8.0.4
  octokit: ^5.0.3
  only-allow: ^1.2.1
  open: ^10.1.2
  openapi-typescript: ^7.8.0
  ora: ^8.2.0
  p-all: ^5.0.0
  p-map: ^7.0.3
  p-throttle: 7.0.0
  parse-json: ^8.3.0
  postgres: ^3.4.7
  prettier: ^3.5.3
  restore-cursor: ^5.1.0
  semver: ^7.7.2
  simple-git-hooks: ^2.13.0
  stripe: ^18.2.0
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.3
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unconfig: ^7.3.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
  wrangler: ^4.18.0
  zod: ^3.25.36
  zod-to-json-schema: ^3.24.5
  zod-validation-error: ^3.4.1
