packages:
  - packages/*
  - apps/*
  - examples/*
  - packages/fixtures/valid/*
ignoredBuiltDependencies:
  - '@fisch0920/config'
onlyBuiltDependencies:
  - '@sentry/cli'
catalog:
  '@agentic/core': ^7.6.7
  '@agentic/serper': ^7.6.7
  '@ai-sdk/openai': ^1.3.22
  '@apideck/better-ajv-errors': ^0.3.6
  '@clack/prompts': ^0.11.0
  '@cloudflare/workers-types': ^4.20250620.0
  '@commander-js/extra-typings': ^14.0.0
  '@dotenvx/dotenvx': ^1.45.1
  '@edge-runtime/vm': ^5.0.0
  '@fisch0920/config': ^1.1.3
  '@fisch0920/drizzle-orm': ^0.43.7
  '@fisch0920/drizzle-zod': ^0.7.9
  '@hono/mcp': ^0.1.0
  '@hono/node-server': 1.14.4
  '@hono/sentry': ^1.2.2
  '@hono/zod-openapi': ^0.19.8
  '@hono/zod-validator': ^0.7.0
  '@modelcontextprotocol/sdk': ^1.13.0
  '@number-flow/react': ^0.5.10
  '@paralleldrive/cuid2': ^2.2.2
  '@pmndrs/assets': ^1.7.0
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-tooltip': ^1.2.7
  '@react-email/components': ^0.1.0
  '@react-three/cannon': ^6.6.0
  '@react-three/drei': ^10.2.0
  '@react-three/fiber': ^9.1.2
  '@react-three/postprocessing': ^3.0.4
  '@react-three/rapier': ^2.1.0
  '@redocly/openapi-core': ^1.34.3
  '@sentry/cli': ^2.46.0
  '@sentry/cloudflare': ^9.30.0
  '@sentry/core': ^9.30.0
  '@sentry/node': ^9.30.0
  '@standard-schema/spec': ^1.0.0
  '@tailwindcss/postcss': ^4.1.10
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/react-form': ^1.12.3
  '@tanstack/react-query': ^5.80.10
  '@tanstack/react-query-devtools': ^5.80.10
  '@types/canvas-confetti': ^1.9.0
  '@types/ms': ^2.1.0
  '@types/node': ^24.0.4
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/semver': ^7.7.0
  '@types/three': ^0.177.0
  agents: ^0.0.95
  ai: ^4.3.15
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  autoprefixer: ^10.4.21
  bcryptjs: ^3.0.2
  bumpp: ^10.2.0
  camelcase: ^8.0.0
  canvas-confetti: ^1.9.3
  class-variance-authority: ^0.7.1
  cleye: ^1.3.4
  clsx: ^2.1.1
  commander: ^14.0.0
  conf: ^14.0.0
  decamelize: ^6.0.0
  decircular: ^1.0.0
  del-cli: ^6.0.0
  dotenv: ^16.5.0
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  email-validator: ^2.0.4
  eslint: ^9.29.0
  eslint-plugin-drizzle: ^0.2.3
  eventid: ^2.0.1
  exit-hook: 4.0.0
  fast-content-type-parse: ^3.0.0
  fast-uri: ^3.0.6
  fastmcp: ^3.4.0
  get-port: ^7.1.0
  hash-object: ^5.0.1
  hast-util-to-jsx-runtime: ^2.3.6
  hono: 4.8.1
  is-obj: ^3.0.0
  is-relative-url: ^4.0.0
  knip: ^5.61.2
  ky: 1.8.1
  lint-staged: ^16.1.2
  lucide-react: ^0.518.0
  motion: ^12.18.1
  ms: ^2.1.3
  next: ^15.3.4
  next-themes: ^0.4.6
  npm-run-all2: ^8.0.4
  octokit: ^5.0.3
  only-allow: ^1.2.1
  open: ^10.1.2
  openapi-typescript: ^7.8.0
  ora: ^8.2.0
  p-all: ^5.0.0
  p-map: 7.0.3
  p-throttle: 7.0.0
  p-times: ^4.0.0
  parse-json: ^8.3.0
  plur: ^5.1.0
  postcss: ^8.5.6
  postgres: ^3.4.7
  posthog-js: ^1.255.0
  prettier: ^3.6.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-email: ^4.0.16
  react-infinite-scroll-hook: ^6.0.1
  react-lottie-player: ^2.1.0
  react-use: ^17.6.0
  resend: ^4.6.0
  restore-cursor: ^5.1.0
  semver: ^7.7.2
  server-only: ^0.0.1
  shiki: ^3.7.0
  simple-git-hooks: ^2.13.0
  sonner: ^2.0.5
  sort-keys: ^5.1.0
  stripe: ^18.2.1
  suspend-react: ^0.1.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.10
  three: ^0.177.0
  tsup: ^8.5.0
  tsx: ^4.20.3
  turbo: ^2.5.4
  tw-animate-css: ^1.3.4
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unconfig: ^7.3.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  wrangler: ^4.21.0
  zod: ^3.25.67
  zod-to-json-schema: ^3.24.5
  zod-validation-error: ^3.5.2
